[owner]
name = "Uriel Rivero"

[package]
name = "tasks-and-notes-backend"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros" ] }
