[owner]
name = "Tom Preston-Werner"

[package]
name = "tasks-and-notes-backend"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "2.1.4"
